version: '3'

services:
  # Discord Voice Announcer Bot Service
  discord-voice-announcer:
    image: haggbart/discord-voice-announcer-unraid:latest
    container_name: discord-voice-announcer
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}             # Load from .env file
      - TZ=${TZ:-Europe/Oslo}                      # Load from .env with fallback
      - PUID=99                                    # Optional: User ID for file permissions
      - PGID=100                                   # Optional: Group ID for file permissions
      - VOICE_LANGUAGE=${VOICE_LANGUAGE:-en}       # Load from .env with fallback
      - COMMAND_PREFIX=${COMMAND_PREFIX:-!}        # Load from .env with fallback
      - ANNOUNCE_JOINS=${ANNOUNCE_JOINS:-True}     # Load from .env with fallback
      - ANNOUNCE_LEAVES=${ANNOUNCE_LEAVES:-True}   # Load from .env with fallback
      - WHITELIST_MODE=${WHITELIST_MODE:-False}    # Load from .env with fallback
    volumes:
      - ./data:/app/data                           # Persistent storage for announcements and whitelist
      # For Unraid users, you might want to use a specific path like:
      # - /mnt/user/appdata/discord-voice-announcer:/app/data
    restart: unless-stopped
    networks:
      - discord-voice-net
    deploy:
      resources:
        limits:
          memory: 256M
          
  # Web Interface Service
  discord-voice-web:
    build: 
      context: ./web
      dockerfile: Dockerfile
    container_name: discord-voice-web
    ports:
      - "5000:5000"                                # Expose web interface on port 5000
    environment:
      - FLASK_ENV=production
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}       # Load from .env file
      - DATA_DIR=/app/data
      - BOT_CONTAINER_NAME=discord-voice-announcer
      - PORT=5000
    volumes:
      - ./data:/app/data                           # Share the same data volume with the bot
      - /var/run/docker.sock:/var/run/docker.sock:ro  # Access to Docker socket for controlling bot container
    # Use Docker socket group permissions from host
    group_add:
      - "${DOCKER_GID:-999}"                       # Default Docker GID is 999 on many systems; override with DOCKER_GID env var
    depends_on:
      - discord-voice-announcer
    restart: unless-stopped
    networks:
      - discord-voice-net
    deploy:
      resources:
        limits:
          memory: 128M

# Define a shared network for both containers
networks:
  discord-voice-net:
    driver: bridge

